on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_push:
    runs-on: ubuntu-24.04 [Beta]
    permissions:
      packages: write
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/uinta-labs/pando/agent:${{ github.sha }}
